/** Editable content, grouped by page/section. Each field's `default` is the
 *  current on-site text — the single source of truth for the editor + fallback. */
export const CONTENT_GROUPS = [
  {
    id: 'home-hero', title: 'Homepage — Hero',
    fields: [
      { key: 'home.hero.title', label: 'Headline', type: 'text',
        default: 'Premium Property Maintenance, Landscaping & Cleaning in Adelaide' },
      { key: 'home.hero.subtitle', label: 'Subtitle', type: 'richtext',
        default: 'Reliable, fully insured services for commercial sites, builders, real estate, homes and outdoor spaces.' },
      { key: 'home.hero.ctaPrimary', label: 'Primary button text', type: 'text',
        default: 'Get a Free Quote' },
      { key: 'home.hero.trust', label: 'Trust badges', type: 'list', itemType: 'text',
        default: ['Fully Insured', 'Police Checked', 'Adelaide Based', 'Commercial & Residential'] },
    ],
  },
  {
    id: 'home-faq', title: 'Homepage — FAQ',
    fields: [
      { key: 'faq.heading', label: 'Section heading', type: 'text',
        default: 'Frequently Asked Questions' },
      { key: 'faq.subheading', label: 'Sub-heading', type: 'text',
        default: 'Everything you need to know about our services' },
      { key: 'faq.items', label: 'Questions & answers', type: 'listObject',
        itemFields: [
          { key: 'question', label: 'Question', type: 'text' },
          { key: 'answer', label: 'Answer', type: 'richtext' },
        ],
        default: [
          { question: 'What areas do you service?',
            answer: 'We currently provide professional cleaning and landscaping services across Adelaide and Sydney and their surrounding suburbs.' },
          { question: 'Are your team members insured and police-checked?',
            answer: 'Yes, our team members are professionally selected and committed to providing safe, reliable and high-quality service.' },
          { question: 'Do I need to be home for the service?',
            answer: "It's entirely up to you. Many of our clients provide access instructions or keys for when they are at work. We ensure your property is secure at all times." },
          { question: 'What is your satisfaction guarantee?',
            answer: 'We pride ourselves on quality. If you are not completely satisfied with our service, please contact us within 24 hours and we will return to rectify the issue at no extra cost.' },
          { question: 'Do you bring your own cleaning supplies?',
            answer: "Yes, we bring all necessary eco-friendly cleaning products and professional-grade equipment. If you have specific products you'd like us to use, just let us know!" },
        ] },
    ],
  },
  {
    id: 'home-why', title: 'Homepage — Why Choose',
    fields: [
      { key: 'home.why.heading', label: 'Section heading', type: 'text', default: 'Why Choose Prestiva?' },
      { key: 'home.why.subheading', label: 'Sub-heading', type: 'text', default: 'A higher standard of service in every space we touch' },
      { key: 'home.why.items', label: 'Reasons', type: 'listObject',
        itemFields: [
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'richtext' },
        ],
        default: [
          { title: 'Police-checked & Fully Insured', text: 'Every team member is vetted and covered, giving you total peace of mind.' },
          { title: 'Eco-friendly Products', text: 'We use sustainable, non-toxic products that are safe for your family, staff, and pets.' },
          { title: 'Upfront Pricing', text: 'No hidden costs. We provide clear, transparent quotes before any work begins.' },
          { title: 'Same-day Bookings', text: 'Need it done fast? We offer flexible scheduling and urgent cleaning services.' },
          { title: 'Satisfaction Guarantee', text: "If you're not 100% happy with the results, we'll make it right — guaranteed." },
        ] },
    ],
  },
  {
    id: 'home-reviews', title: 'Homepage — Reviews',
    fields: [
      { key: 'home.reviews.heading', label: 'Section heading', type: 'text', default: 'What Our Clients Say' },
      { key: 'home.reviews.subheading', label: 'Sub-heading', type: 'text', default: 'Real feedback from satisfied property owners' },
      { key: 'home.reviews.items', label: 'Reviews', type: 'listObject',
        itemFields: [
          { key: 'name', label: 'Name', type: 'text' },
          { key: 'role', label: 'Role / location', type: 'text' },
          { key: 'rating', label: 'Rating (1-5)', type: 'text' },
          { key: 'text', label: 'Review', type: 'textarea' },
        ],
        default: [
          { name: 'David H.', role: 'Property Manager, Adelaide', rating: 5, text: 'Prestiva has been managing our office cleaning for over a year. Their attention to detail is unmatched, and they are incredibly reliable. Highly recommend!' },
          { name: 'Sarah L.', role: 'Homeowner, Sydney', rating: 5, text: 'Booked an end-of-lease clean and was blown away. I got my full bond back without a single issue. The team was professional and friendly.' },
          { name: 'Mark T.', role: 'Restaurant Owner', rating: 5, text: 'Consistency is key in my business, and Prestiva delivers every time. Our kitchen and dining area look pristine every morning.' },
          { name: 'Jess M.', role: 'Airbnb Host, Adelaide', rating: 5, text: 'Fast turnarounds between guests and a spotless result every single time. My listing reviews have never been better since switching to Prestiva.' },
          { name: 'Tony R.', role: 'Builder, Sydney', rating: 5, text: 'Their after-construction clean got our site handover-ready ahead of schedule. Thorough, careful and great to deal with on busy projects.' },
          { name: 'Priya S.', role: 'Homeowner, Adelaide Hills', rating: 5, text: 'They mow, weed and keep our gardens immaculate. Same friendly crew each visit and the green waste is always taken away. Couldn’t be happier.' },
        ] },
    ],
  },
  {
    id: 'home-addons', title: 'Homepage — Add-On Services',
    fields: [
      { key: 'home.addons.heading', label: 'Section heading', type: 'text', default: 'Add-On Services' },
      { key: 'home.addons.subheading', label: 'Sub-heading', type: 'text', default: 'Customise your cleaning with these extra services' },
      { key: 'home.addons.items', label: 'Add-on names', type: 'list', itemType: 'text',
        default: ['Oven Clean', 'Window Clean', 'Carpet Steam', 'Fridge Clean', 'Balcony Clean', 'Blind Clean', 'Wall Washing', 'Garage Tidy', 'Pressure Wash', 'Mulching'] },
    ],
  },
  {
    id: 'home-checklist', title: 'Homepage — Cleaning Checklist',
    fields: [
      { key: 'home.checklist.heading', label: 'Section heading', type: 'text', default: 'What’s Included in Every Clean' },
      { key: 'home.checklist.subheading', label: 'Sub-heading', type: 'text', default: 'Our comprehensive checklist ensures no corner is missed' },
      { key: 'home.checklist.kitchen', label: 'Kitchen items', type: 'list', itemType: 'text',
        default: ['Benchtop and splashback cleaned', 'Sinks and taps sanitised and polished', 'Stovetop thoroughly cleaned', 'Exterior of oven and rangehood cleaned', 'Exterior of cupboards and drawers wiped', 'Microwave cleaned inside and out'] },
      { key: 'home.checklist.bathrooms', label: 'Bathrooms items', type: 'list', itemType: 'text',
        default: ['Shower, bathtub and tiles scrubbed', 'Toilets sanitised and cleaned', 'Vantiy and mirrors polished', 'Sinks and taps sanitised', 'Cabinets wiped down', 'Towel rails and light switches cleaned'] },
      { key: 'home.checklist.bedrooms', label: 'Bedrooms items', type: 'list', itemType: 'text',
        default: ['All surfaces dusted and wiped', 'Mirrors and glass surfaces cleaned', 'Window sills and tracks wiped', 'Light switches and door handles cleaned', 'Skirting boards dusted', 'Carpets vacuumed or floors mopped'] },
      { key: 'home.checklist.living', label: 'Living areas items', type: 'list', itemType: 'text',
        default: ['General dusting of all surfaces', 'Electronics dusted carefully', 'Coffee tables and dining areas cleaned', 'Upholstery vacuumed', 'Floor areas thoroughly cleaned', 'Internal cobwebs removed'] },
    ],
  },
  {
    id: 'home-commercial', title: 'Homepage — Commercial Spotlight',
    fields: [
      { key: 'home.commercial.eyebrow', label: 'Eyebrow label', type: 'text', default: 'Commercial & Builders' },
      { key: 'home.commercial.heading', label: 'Heading', type: 'text', default: 'Commercial Cleaning Specialists' },
      { key: 'home.commercial.body', label: 'Body paragraph', type: 'richtext',
        default: 'Prestiva Property Services provides reliable commercial cleaning for offices, retail spaces, construction sites and business premises. We offer once-off, after-hours and regular maintenance cleaning tailored to each site.' },
      { key: 'home.commercial.points', label: 'Points', type: 'list', itemType: 'text',
        default: ['Office & retail cleaning', 'Builders & after-construction cleaning', 'After-hours availability', 'Insured team', 'Flexible maintenance plans', 'Professional equipment'] },
      { key: 'home.commercial.button', label: 'Button text', type: 'text', default: 'Commercial Services' },
    ],
  },
  {
    id: 'home-pricing', title: 'Homepage — Pricing',
    fields: [
      { key: 'home.pricing.heading', label: 'Section heading', type: 'text', default: 'Simple, Transparent Pricing' },
      { key: 'home.pricing.subheading', label: 'Sub-heading', type: 'text', default: 'Premium quality service with no hidden costs' },
      { key: 'home.pricing.p1.title', label: 'Plan 1 — title', type: 'text', default: 'Property Maintenance' },
      { key: 'home.pricing.p1.price', label: 'Plan 1 — price', type: 'text', default: 'From $65' },
      { key: 'home.pricing.p1.unit', label: 'Plan 1 — unit', type: 'text', default: '/service' },
      { key: 'home.pricing.p1.features', label: 'Plan 1 — features', type: 'list', itemType: 'text',
        default: ['Lawn mowing', 'Weeding & edging', 'Gutter cleaning', 'Pressure cleaning', 'Green waste removal', 'Site clean-ups'] },
      { key: 'home.pricing.p1.button', label: 'Plan 1 — button', type: 'text', default: 'Get Maintenance Quote' },
      { key: 'home.pricing.p2.title', label: 'Plan 2 — title', type: 'text', default: 'Landscaping' },
      { key: 'home.pricing.p2.price', label: 'Plan 2 — price', type: 'text', default: 'From $99' },
      { key: 'home.pricing.p2.unit', label: 'Plan 2 — unit', type: 'text', default: '/service' },
      { key: 'home.pricing.p2.features', label: 'Plan 2 — features', type: 'list', itemType: 'text',
        default: ['Turf laying', 'Irrigation', 'Soil preparation', 'Lawn repair', 'Garden clean-up', 'Outdoor area preparation'] },
      { key: 'home.pricing.p2.button', label: 'Plan 2 — button', type: 'text', default: 'Get Landscaping Quote' },
      { key: 'home.pricing.p3.title', label: 'Plan 3 — title', type: 'text', default: 'Cleaning Services' },
      { key: 'home.pricing.p3.price', label: 'Plan 3 — price', type: 'text', default: 'From $120' },
      { key: 'home.pricing.p3.unit', label: 'Plan 3 — unit', type: 'text', default: '/service' },
      { key: 'home.pricing.p3.features', label: 'Plan 3 — features', type: 'list', itemType: 'text',
        default: ['End-of-lease cleaning', 'Builders cleaning', 'After-construction cleaning', 'Deep cleaning', 'Carpet cleaning', 'Window cleaning'] },
      { key: 'home.pricing.p3.button', label: 'Plan 3 — button', type: 'text', default: 'Get Cleaning Quote' },
      { key: 'home.pricing.p4.title', label: 'Plan 4 — title', type: 'text', default: 'Commercial Cleaning' },
      { key: 'home.pricing.p4.price', label: 'Plan 4 — price', type: 'text', default: 'From $35' },
      { key: 'home.pricing.p4.unit', label: 'Plan 4 — unit', type: 'text', default: '/hour' },
      { key: 'home.pricing.p4.features', label: 'Plan 4 — features', type: 'list', itemType: 'text',
        default: ['Office cleaning', 'Retail cleaning', 'After-hours cleaning', 'Regular maintenance plans', 'Fully insured team', 'Police checked staff'] },
      { key: 'home.pricing.p4.button', label: 'Plan 4 — button', type: 'text', default: 'Get Commercial Quote' },
    ],
  },
  {
    id: 'home-results', title: 'Homepage — Results Reel',
    fields: [
      { key: 'home.results.heading', label: 'Section heading', type: 'text', default: 'See the Results' },
      { key: 'home.results.subheading', label: 'Sub-heading', type: 'text', default: 'Real footage from our recent jobs — tap to play.' },
      { key: 'home.results.button', label: 'Button text', type: 'text', default: 'View Full Gallery' },
    ],
  },
  {
    id: 'home-services', title: 'Homepage — Services Overview',
    fields: [
      { key: 'home.services.heading', label: 'Section heading', type: 'text', default: 'Our Service Specialisations' },
      { key: 'home.services.subheading', label: 'Sub-heading', type: 'text', default: 'Comprehensive property care tailored to your needs' },
      { key: 'home.services.linkText', label: 'Card link text', type: 'text', default: 'Learn More' },
    ],
  },
  {
    id: 'home-about', title: 'Homepage — About (Mini)',
    fields: [
      { key: 'home.about.eyebrow', label: 'Eyebrow label', type: 'text', default: 'Local & Reliable' },
      { key: 'home.about.heading', label: 'Heading', type: 'text', default: 'A Local Team You Can Trust' },
      { key: 'home.about.body1', label: 'Paragraph 1', type: 'richtext',
        default: 'Prestiva Property Services was founded on a clear standard — to deliver a level of reliability, detail, and professionalism that clients can consistently depend on. We are a family-owned business serving Adelaide & Sydney with pride.' },
      { key: 'home.about.body2', label: 'Paragraph 2', type: 'richtext',
        default: "Whether it's your home, office, or garden, we treat every space with the respect it deserves. Our team is fully insured, police-checked, and committed to your satisfaction." },
      { key: 'home.about.button', label: 'Button text', type: 'text', default: 'Learn Our Story' },
    ],
  },
  {
    id: 'home-cta', title: 'Homepage — Call to Action',
    fields: [
      { key: 'home.cta.heading', label: 'Heading', type: 'text', default: 'Ready to Book?' },
      { key: 'home.cta.subtitle', label: 'Subtitle', type: 'text', default: 'Get your free, no-obligation quote today and experience the Prestiva difference.' },
      { key: 'home.cta.primaryButton', label: 'Primary button', type: 'text', default: 'Get a Free Quote' },
      { key: 'home.cta.callButton', label: 'Call button', type: 'text', default: 'Call Now' },
    ],
  },
  {
    id: 'home-areas', title: 'Homepage — Service Areas',
    fields: [
      { key: 'home.areas.heading', label: 'Section heading', type: 'text', default: 'We Come to You' },
      { key: 'home.areas.subheading', label: 'Sub-heading', type: 'text', default: 'Serving major metropolitan areas across Australia' },
      { key: 'home.areas.items', label: 'Areas', type: 'listObject',
        itemFields: [
          { key: 'city', label: 'City', type: 'text' },
          { key: 'region', label: 'Region (optional)', type: 'text' },
          { key: 'suburbs', label: 'Suburbs', type: 'textarea' },
        ],
        default: [
          { city: 'Adelaide', region: 'Greater Adelaide Metropolitan Area', suburbs: 'CBD • Northern Suburbs • Southern Suburbs • Eastern Suburbs • Western Suburbs' },
          { city: 'Sydney', region: '', suburbs: 'CBD, Inner West, Eastern Suburbs, North Shore & Greater Sydney' },
        ] },
    ],
  },
  {
    id: 'home-trust', title: 'Homepage — Trust Stats (labels)',
    fields: [
      { key: 'home.trust.label1', label: 'Stat 1 label', type: 'text', default: 'Properties Serviced' },
      { key: 'home.trust.label2', label: 'Stat 2 label', type: 'text', default: 'Google Rated' },
      { key: 'home.trust.label3', label: 'Stat 3 label', type: 'text', default: '& Police Checked' },
      { key: 'home.trust.label4', label: 'Stat 4 label', type: 'text', default: 'A Week' },
    ],
  },
  {
    id: 'home-who', title: 'Homepage — Who We Work With',
    fields: [
      { key: 'home.who.heading', label: 'Section heading', type: 'text', default: 'Who We Work With' },
      { key: 'home.who.subheading', label: 'Sub-heading', type: 'text', default: 'Trusted by businesses, trades and homeowners across Adelaide & Sydney' },
      { key: 'home.who.items', label: 'Client types', type: 'list', itemType: 'text',
        default: ['Builders & Contractors', 'Real Estate Agents', 'Offices & Retail Stores', 'Property Managers', 'Homeowners', 'Commercial Sites'] },
    ],
  },
  {
    id: 'page-about', title: 'About Page',
    fields: [
      { key: 'about.hero.title', label: 'Hero title', type: 'text', default: 'Your Partner in Property Excellence' },
      { key: 'about.hero.subtitle', label: 'Hero subtitle', type: 'text', default: 'Serving Adelaide & Sydney with pride and professional care.' },
      { key: 'about.hero.button', label: 'Hero button', type: 'text', default: 'Call Us' },
      { key: 'about.story.heading', label: 'Story heading', type: 'text', default: 'Our Story' },
      { key: 'about.story.p1', label: 'Story paragraph 1', type: 'richtext', default: 'Prestiva Property Services was founded on a clear standard — to deliver a level of reliability, detail, and professionalism that clients can consistently depend on.' },
      { key: 'about.story.p2', label: 'Story paragraph 2', type: 'richtext', default: 'After seeing how often services were rushed, inconsistent, or lacking accountability, we set out to build something different. A service where every job is approached with care, every space is treated with respect, and every client receives the attention they deserve.' },
      { key: 'about.story.p3', label: 'Story paragraph 3', type: 'richtext', default: 'From a small, hands-on operation, Prestiva has grown into a trusted provider working with businesses, property managers, and homeowners across Adelaide & Sydney. What remains unchanged is our commitment to quality, consistency, and doing the job properly — not just quickly.' },
      { key: 'about.story.p4', label: 'Story paragraph 4', type: 'richtext', default: 'We believe a well-maintained space reflects the people behind it. That’s why we focus not only on results, but on delivering a service experience that is professional, dependable, and built for long-term relationships.' },
      { key: 'about.values.heading', label: 'Values heading', type: 'text', default: 'Our Values' },
      { key: 'about.values.items', label: 'Values', type: 'listObject',
        itemFields: [
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'desc', label: 'Description', type: 'richtext' },
        ],
        default: [
          { title: 'Reliability', desc: 'We show up on time and deliver consistent results you can depend on.' },
          { title: 'Quality Workmanship', desc: 'Every job is approached with care and finished to the highest standard.' },
          { title: 'Eco-Conscious', desc: 'We use sustainable products that are safe for you and the environment.' },
          { title: 'Customer First', desc: 'Our service is built around your specific needs and long-term satisfaction.' },
        ] },
      { key: 'about.badges', label: 'Trust badges', type: 'list', itemType: 'text',
        default: ['Fully Insured', 'Police Checked', 'Guarantee', '5-Star Rated'] },
      { key: 'about.cta.heading', label: 'CTA heading', type: 'text', default: 'Ready to Get Started?' },
      { key: 'about.cta.text', label: 'CTA text', type: 'text', default: 'Contact our friendly team for a free consultation.' },
      { key: 'about.cta.primaryButton', label: 'CTA primary button', type: 'text', default: 'Get a Free Quote' },
      { key: 'about.cta.callButton', label: 'CTA call button', type: 'text', default: 'Call Now' },
    ],
  },
  {
    id: 'page-commercial', title: 'Commercial Page',
    fields: [
      { key: 'commercial.hero.title', label: 'Hero title', type: 'text', default: 'Professional Commercial Cleaning — Adelaide & Sydney' },
      { key: 'commercial.hero.quoteButton', label: 'Hero quote button', type: 'text', default: 'Get a Commercial Quote' },
      { key: 'commercial.hero.callButton', label: 'Hero call button', type: 'text', default: 'Call Now' },
      { key: 'commercial.industries.heading', label: 'Industries heading', type: 'text', default: 'Who We Clean For' },
      { key: 'commercial.industries.subheading', label: 'Industries sub-heading', type: 'text', default: 'Expert cleaning solutions across diverse industries' },
      { key: 'commercial.industries.items', label: 'Industries', type: 'list', itemType: 'text',
        default: ['Offices', 'Restaurants', 'After Builders', 'Medical', 'Retail', 'Warehouses', 'Strata', 'Contract Cleaning'] },
      { key: 'commercial.included.heading', label: 'What\'s Included heading', type: 'text', default: "What's Included" },
      { key: 'commercial.included.subheading', label: 'What\'s Included sub-heading', type: 'text', default: 'Detailed cleaning for every area of your business' },
      { key: 'commercial.included.col1Title', label: 'Column 1 title', type: 'text', default: 'Office & Working Areas' },
      { key: 'commercial.included.col1Items', label: 'Column 1 items', type: 'list', itemType: 'text',
        default: ['Dusting & sanitising all desks & surfaces', 'Emptying bins & replacing liners', 'Cleaning glass partitions & internal windows', 'Vacuuming all carpets & mopping hard floors'] },
      { key: 'commercial.included.col2Title', label: 'Column 2 title', type: 'text', default: 'Kitchens & Bathrooms' },
      { key: 'commercial.included.col2Items', label: 'Column 2 items', type: 'list', itemType: 'text',
        default: ['Deep clean of all bathroom fixtures', 'Refilling soap & paper dispensers', 'Sanitising kitchen benchtops & sinks', 'Cleaning exterior of appliances & cupboards'] },
      { key: 'commercial.pricing.heading', label: 'Pricing heading', type: 'text', default: 'Commercial Pricing' },
      { key: 'commercial.cta.heading', label: 'CTA heading', type: 'text', default: 'Request a Commercial Quote' },
      { key: 'commercial.cta.text', label: 'CTA text', type: 'text', default: 'Speak with our contract cleaning specialists today.' },
      { key: 'commercial.cta.primaryButton', label: 'CTA primary button', type: 'text', default: 'Get a Quote' },
      { key: 'commercial.cta.callButton', label: 'CTA call button', type: 'text', default: 'Call Now' },
    ],
  },
  {
    id: 'page-residential', title: 'Residential Page',
    fields: [
      { key: 'residential.hero.title', label: 'Hero title', type: 'text', default: 'Professional Home Cleaning — Adelaide & Sydney' },
      { key: 'residential.hero.quoteButton', label: 'Hero quote button', type: 'text', default: 'Get a Home Clean Quote' },
      { key: 'residential.hero.callButton', label: 'Hero call button', type: 'text', default: 'Call Now' },
      { key: 'residential.services.heading', label: 'Services heading', type: 'text', default: 'Our Home Cleaning Services' },
      { key: 'residential.services.items', label: 'Services', type: 'listObject',
        itemFields: [
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'desc', label: 'Description', type: 'richtext' },
        ],
        default: [
          { title: 'House Cleaning', desc: 'Regular maintenance for a spotless home.' },
          { title: 'End of Lease', desc: 'Professional cleaning for a full bond refund.' },
          { title: 'Deep Clean', desc: 'Thorough sanitisation for a fresh start.' },
          { title: 'Move In/Out', desc: 'Seamless cleaning for your transition.' },
          { title: 'Carpet Steam', desc: 'Removal of stains and allergens.' },
          { title: 'Spring Clean', desc: 'Reviving your home for the new season.' },
        ] },
      { key: 'residential.bond.heading', label: 'Bond section heading', type: 'text', default: '100% Bond Back Guarantee' },
      { key: 'residential.bond.body', label: 'Bond body', type: 'richtext', default: 'Moving out? Leave the hard work to us. Our End of Lease cleaning service is designed to meet the strict standards of real estate agents and landlords.' },
      { key: 'residential.bond.items', label: 'Bond points', type: 'list', itemType: 'text',
        default: ['72-Hour re-clean guarantee', 'Agency-approved checklist', 'Professional equipment used'] },
      { key: 'residential.bond.cardTitle', label: 'Bond card title', type: 'text', default: 'Fully Guaranteed' },
      { key: 'residential.checklist.heading', label: 'Checklist heading', type: 'text', default: 'Room-by-Room Checklist' },
      { key: 'residential.checklist.kitchen', label: 'Checklist — kitchen', type: 'list', itemType: 'text',
        default: ['Oven Exterior', 'Stovetop', 'Countertops', 'Sinks & Taps', 'Cupboard Faces'] },
      { key: 'residential.checklist.living', label: 'Checklist — living', type: 'list', itemType: 'text',
        default: ['Dusting', 'Vacuuming', 'Glass Surfaces', 'Skirting Boards', 'Door Handles'] },
      { key: 'residential.checklist.bathrooms', label: 'Checklist — bathrooms', type: 'list', itemType: 'text',
        default: ['Showers', 'Vanity', 'Toilets', 'Mirrors', 'Towel Rails'] },
      { key: 'residential.checklist.balcony', label: 'Checklist — balcony', type: 'list', itemType: 'text',
        default: ['Sweeping', 'Railing Wipe', 'Glass Door Tracks', 'General Tidy'] },
      { key: 'residential.pricing.heading', label: 'Pricing heading', type: 'text', default: 'Transparent Home Pricing' },
      { key: 'residential.cta.heading', label: 'CTA heading', type: 'text', default: 'Book a Cleaning Service' },
      { key: 'residential.cta.text', label: 'CTA text', type: 'text', default: 'Ready to enjoy a sparkling clean home?' },
      { key: 'residential.cta.primaryButton', label: 'CTA primary button', type: 'text', default: 'Get Cleaning Quote' },
      { key: 'residential.cta.callButton', label: 'CTA call button', type: 'text', default: 'Call Now' },
    ],
  },
  {
    id: 'page-landscaping', title: 'Landscaping Page',
    fields: [
      { key: 'landscaping.hero.title', label: 'Hero title', type: 'text', default: 'Landscaping & Garden Services — Adelaide & Sydney' },
      { key: 'landscaping.hero.quoteButton', label: 'Hero quote button', type: 'text', default: 'Get Landscaping Quote' },
      { key: 'landscaping.hero.callButton', label: 'Hero call button', type: 'text', default: 'Call Now' },
      { key: 'landscaping.services.heading', label: 'Services heading', type: 'text', default: 'Our Garden Services' },
      { key: 'landscaping.why.heading', label: 'Why-choose heading', type: 'text', default: 'Why Choose Prestiva?' },
      { key: 'landscaping.why.subheading', label: 'Why-choose sub-heading', type: 'text', default: 'Reliable outdoor maintenance for your property' },
      { key: 'landscaping.why.items', label: 'Why-choose cards', type: 'listObject',
        itemFields: [
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'richtext' },
        ],
        default: [
          { title: 'Same Crew', text: 'We send the same team to your property for consistent results every time.' },
          { title: 'Green Removal', text: 'We include full green waste removal in every booking, leaving your site pristine.' },
          { title: 'One-off or Regular', text: "Whether you need a quick clean-up or monthly maintenance, we've got you covered." },
        ] },
      { key: 'landscaping.pricing.heading', label: 'Pricing heading', type: 'text', default: 'Transparent Gardening Pricing' },
      { key: 'landscaping.pricing.intro', label: 'Pricing intro', type: 'richtext', default: 'Clear, upfront starting prices — no hidden fees. Your exact quote is always free and tailored to your garden.' },
      { key: 'landscaping.pricing.footnote', label: 'Pricing footnote', type: 'text', default: '* Starting estimates. Final pricing is confirmed in your free, no-obligation quote.' },
      { key: 'landscaping.cta.heading', label: 'CTA heading', type: 'text', default: 'Book a Landscaping Service' },
      { key: 'landscaping.cta.text', label: 'CTA text', type: 'text', default: 'Ready to transform your outdoor space?' },
      { key: 'landscaping.cta.primaryButton', label: 'CTA primary button', type: 'text', default: 'Get Landscaping Quote' },
      { key: 'landscaping.cta.callButton', label: 'CTA call button', type: 'text', default: 'Call Now' },
    ],
  },
  {
    id: 'page-servicecat', title: 'Service Category Pages (Cleaning / Property Maintenance)',
    fields: [
      { key: 'servicecat.hero.priceLabel', label: 'Hero "starting from" label', type: 'text', default: 'Starting from' },
      { key: 'servicecat.hero.quoteButton', label: 'Hero quote button', type: 'text', default: 'Get a Free Quote' },
      { key: 'servicecat.hero.callButton', label: 'Hero call button', type: 'text', default: 'Call Now' },
      { key: 'servicecat.services.heading', label: 'Services heading', type: 'text', default: 'What We Offer' },
      { key: 'servicecat.card.learnMore', label: 'Card "learn more" text', type: 'text', default: 'Learn more' },
      { key: 'servicecat.card.getQuote', label: 'Card "get a quote" text', type: 'text', default: 'Get a quote' },
      { key: 'servicecat.card.comingSoon', label: 'Card "coming soon" badge', type: 'text', default: 'Coming Soon' },
      { key: 'servicecat.cta.text', label: 'CTA text', type: 'text', default: "Tell us what you need — we'll tailor a no-obligation quote." },
      { key: 'servicecat.cta.primaryButton', label: 'CTA primary button', type: 'text', default: 'Get a Free Quote' },
      { key: 'servicecat.cta.callButton', label: 'CTA call button', type: 'text', default: 'Call Now' },
    ],
  },
  {
    id: 'page-privacy', title: 'Privacy Policy Page',
    fields: [
      { key: 'privacy.title', label: 'Page title', type: 'text', default: 'Privacy Policy' },
      { key: 'privacy.intro', label: 'Intro', type: 'richtext', default: 'Prestiva Property Services ("we", "us", "our") respects your privacy and is committed to protecting the personal information you share with us. This policy explains what we collect and how we use it.' },
      { key: 'privacy.s1.heading', label: 'Section 1 heading', type: 'text', default: 'Information we collect' },
      { key: 'privacy.s1.body', label: 'Section 1 body', type: 'richtext', default: 'When you submit our quote or contact form, we collect the details you provide — such as your name, phone number, email address, service required, and the suburb or location of the job.' },
      { key: 'privacy.s2.heading', label: 'Section 2 heading', type: 'text', default: 'How we use your information' },
      { key: 'privacy.s2.items', label: 'Section 2 list', type: 'list', itemType: 'text',
        default: ['To respond to your enquiry and provide a quote.', 'To arrange and deliver the services you request.', 'To contact you about your booking or related services.'] },
      { key: 'privacy.s3.heading', label: 'Section 3 heading', type: 'text', default: 'Sharing & third parties' },
      { key: 'privacy.s3.body', label: 'Section 3 body', type: 'richtext', default: 'We do not sell your personal information. Form submissions are delivered to us by email using a secure email provider. Our location picker uses OpenStreetMap/Nominatim and map tiles to help you identify the job address. We only share information where necessary to deliver our services or as required by law.' },
      { key: 'privacy.s4.heading', label: 'Section 4 heading', type: 'text', default: 'Data retention' },
      { key: 'privacy.s4.body', label: 'Section 4 body', type: 'richtext', default: 'We keep enquiry details only as long as needed to respond to you and to provide our services, after which they are removed unless we are required to retain them.' },
      { key: 'privacy.s5.heading', label: 'Section 5 heading', type: 'text', default: 'Your choices' },
      { key: 'privacy.s5.body', label: 'Section 5 body', type: 'richtext', default: 'You can request access to, correction of, or deletion of the personal information we hold about you at any time by contacting us using the details below.' },
      { key: 'privacy.contactHeading', label: 'Contact heading', type: 'text', default: 'Contact us' },
      { key: 'privacy.footer', label: 'Footer note', type: 'text', default: 'This policy may be updated from time to time. Please check this page for the latest version.' },
    ],
  },
  {
    id: 'page-terms', title: 'Terms of Service Page',
    fields: [
      { key: 'terms.title', label: 'Page title', type: 'text', default: 'Terms of Service' },
      { key: 'terms.intro', label: 'Intro', type: 'richtext', default: 'These terms apply to services provided by Prestiva Property Services ("we", "us", "our"). By requesting a quote or booking a service, you agree to the terms below.' },
      { key: 'terms.s1.heading', label: 'Section 1 heading', type: 'text', default: 'Quotes & bookings' },
      { key: 'terms.s1.body', label: 'Section 1 body', type: 'richtext', default: 'Quotes are provided free of charge and are based on the information you supply. Final pricing may be adjusted if the actual scope of work differs from what was described. A booking is confirmed once we agree a date and the scope of work with you.' },
      { key: 'terms.s2.heading', label: 'Section 2 heading', type: 'text', default: 'Service standards' },
      { key: 'terms.s2.body', label: 'Section 2 body', type: 'richtext', default: 'We aim to deliver every job to a high, professional standard. If you are not satisfied with any part of the work, please contact us within 24 hours so we can make it right.' },
      { key: 'terms.s3.heading', label: 'Section 3 heading', type: 'text', default: 'Access & safety' },
      { key: 'terms.s3.body', label: 'Section 3 body', type: 'richtext', default: 'You agree to provide safe and reasonable access to the property and to advise us of any hazards, pets, alarms or special requirements before the service.' },
      { key: 'terms.s4.heading', label: 'Section 4 heading', type: 'text', default: 'Payment' },
      { key: 'terms.s4.body', label: 'Section 4 body', type: 'richtext', default: 'Payment is due on completion of the service unless otherwise agreed in writing. Recurring or contract work may be invoiced on agreed terms.' },
      { key: 'terms.s5.heading', label: 'Section 5 heading', type: 'text', default: 'Cancellations & rescheduling' },
      { key: 'terms.s5.body', label: 'Section 5 body', type: 'richtext', default: "Please give us at least 24 hours' notice to cancel or reschedule a booking so we can offer the slot to another customer." },
      { key: 'terms.s6.heading', label: 'Section 6 heading', type: 'text', default: 'Liability & insurance' },
      { key: 'terms.s6.body', label: 'Section 6 body', type: 'richtext', default: 'We are fully insured. To the extent permitted by law, our liability is limited to re-performing the service or the cost of the service. Nothing in these terms excludes rights you have under the Australian Consumer Law.' },
      { key: 'terms.contactHeading', label: 'Contact heading', type: 'text', default: 'Contact us' },
      { key: 'terms.footer', label: 'Footer note', type: 'text', default: 'These terms may be updated from time to time. Please check this page for the latest version.' },
    ],
  },
  {
    id: 'page-contact', title: 'Contact Page',
    fields: [
      { key: 'contact.hero.title', label: 'Hero title', type: 'text', default: 'Get in Touch with Prestiva' },
      { key: 'contact.hero.subtitle', label: 'Hero subtitle', type: 'text', default: 'Professional support. Fast response. Reliable service.' },
      { key: 'contact.options.heading', label: 'Contact options heading', type: 'text', default: 'Contact Options' },
      { key: 'contact.label.call', label: '"Call Us" label', type: 'text', default: 'Call Us' },
      { key: 'contact.label.email', label: '"Email Us" label', type: 'text', default: 'Email Us' },
      { key: 'contact.label.whatsapp', label: '"WhatsApp" label', type: 'text', default: 'SMS / WhatsApp' },
      { key: 'contact.businessDetails.heading', label: 'Business details heading', type: 'text', default: 'Business Details' },
      { key: 'contact.form.heading', label: 'Form heading', type: 'text', default: 'Request a Free Quote' },
      { key: 'contact.form.intro', label: 'Form intro', type: 'text', default: "Fill in your details and we'll get back to you within 2 hours." },
      { key: 'contact.toast.successTitle', label: 'Success message — bold lead', type: 'text', default: 'Thank you.' },
      { key: 'contact.toast.successBody', label: 'Success message — body', type: 'text', default: 'Your quote request has been received. Our team will contact you shortly.' },
    ],
  },
  {
    id: 'announcements', title: 'Announcement Bar (top ticker)',
    fields: [
      { key: 'announcements.items', label: 'Ticker messages', type: 'list', itemType: 'text',
        default: [
          '🛠️ Property Maintenance Specialists',
          '🌿 Landscaping & Turf',
          '🏢 Commercial & Builders Cleaning',
          '✅ Fully Insured & Police Checked',
          '⭐ 5-Star Google Rated',
          '⏰ 7 Days a Week',
          '📞 Call us at 0403 540 227',
          '📧 Email us at admin@prestiva.com.au',
        ] },
    ],
  },
];

/** Flattened key → default, for the content store. */
export const CONTENT_DEFAULTS = Object.fromEntries(
  CONTENT_GROUPS.flatMap((g) => g.fields.map((f) => [f.key, f.default]))
);
